spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:43200000}
app.ops.master-key=${APP_OPS_MASTER_KEY:0000}
app.ops.booth-keys=${APP_OPS_BOOTH_KEYS:1:1111,2:1111,3:1111,4:1111,5:1111,6:1111,7:1111,8:1111,9:1111,10:1111,11:1111,12:1111,13:1111,14:1111,15:1111,16:1111}
app.ops.shared-booth-key=${APP_OPS_SHARED_BOOTH_KEY:1111}
app.init.simple-demo-credentials=true
app.init.admin.username=${APP_INIT_ADMIN_USERNAME:0000}
app.init.admin.password=${APP_INIT_ADMIN_PASSWORD:0000}
